fuseml/fuseml

- .github/workflows/lint_commit_messages.yml
- .github/workflows/main.yml
Update CI to run on merge and PRs against the main branch and enable
gitlint for PRs.
> ci: Enable fuseml CI on main branch and gitlint for PR

- scripts/knative-install.sh
Maybe nip.io is more reliable.
> ci: Change knative magic dns from xip.io to nip.io

- embedded-files/serving/kfserving.yaml.tmpl
- scripts/kfserving-install.sh
- scripts/kfserving/kfserving-v0.5.1-v1beta1.yaml
- scripts/knative-install.sh
This allows configuring the timeout for the generated Knative revision.
> fix: Install KFServing with v1beta1 API enabled

- .github/workflows/main.yml
fixes: https://github.com/fuseml/fuseml/issues/26
> fix: Do not run CI workflow when there's is no code change

- paas/client.go
Also, make sure the list of deployments is not empty before
trying the modify its values.
> fix: Delete temporary directories after usage

- acceptance/acceptance_suite_test.go
- acceptance/mlflow_test.go
- deployments/tekton.go
- embedded-files/serving/deployment.yaml.tmpl
- embedded-files/serving/kfserving.yaml.tmpl
- embedded-files/serving/seldon_mlflow.yaml.tmpl
- embedded-files/serving/seldon_sklearn.yaml.tmpl
- paas/client.go
Test the deployed model by doing a prediction test.
fixes: https://github.com/fuseml/fuseml/issues/14
> tests: Test the inference service

- deployments/core.go
Do not install it though, as fuseml-installer does not run as root.
Just tell users where it is saved so they can install it themselves.
Closes #96
Depends on https://github.com/fuseml/fuseml-core/pull/51
> feat: Download fuseml-core client

- .github/workflows/release.yml
- Makefile
Add a set of release Makefile targets that create compressed binaries
and hash files.
> fix: add release Makefile targets

- cmd/root.go
- helpers/exec.go
> Remove dependency on 'sh' and 'openssl'

- deployments/core.go
- deployments/gitea.go
- deployments/mlflow.go
- deployments/tekton.go
> feat: Print URLs of deployed services

- embedded-files/fuseml-core-deployment.yaml
...otherwise you end up with a stale dev image running.
> Always pull the fuseml-core dev image

- deployments/core.go
- embedded-files/fuseml-core-deployment.yaml
No need to parse and sed the yaml template. Closes #100
> fix: Create ConfigMap for GITEA and TEKTON URLs

- acceptance/acceptance_suite_test.go
- cmd/internal/client/upgrade.go
- cmd/root.go
- deployments/core.go
- paas/install_client.go
For now, upgrade just the fuseml-core component which is most likely
to get obsolete.
Closes #124
> feat: Added basic Upgrade command

- .github/workflows/release.yml
> fix: Run release action on all branches

- deployments/istio.go
- embedded-files/istio/istio-minimal-operator.yaml
- helpers/exec.go
- paas/install_client.go
Istio is currently requirement, so do not expect users to
run it from external scripts, rather install it together with
other components.
(cherry picked from commit a58e265c617d8b511f6ccf540762db6f7959221e)
Backport of #132
> feat: [0.1] Install istio as a FuseML component

- deployments/core.go
(cherry picked from commit 0d0e58d73cfa7159458d6d7b91771469ed9fb8b4)
Backport of #133
> fix: [0.1] Create ingres if fuseml-core was deployed with traefik

- deployments/core.go
They need to be deleted first.
> fix: Make sure secret and configMap are fresh after upgrade

- Makefile
> fix: [0.1] Set version correctly for released binaries

- docs/blueprints/002-reuse-training-image.md
This PR adds the blueprint detailing the changes required to implement
such feature.
> feat: mlflow: don't rebuild container images if content doesn't change

- scripts/ci/mlflow-e2e.sh
The script should also test training/serving the example tensorflow model.
> ci: Update mlflow-e2e script for tensorflow example

- deployments/extensions.go
- docs/blueprints/001-installation-of-extensions.md
Wait condition could be more complex, mimicing 'kubectl wait' behavior.
> feat: Better handling of wait conditions when installing extensions

- docs/blueprints/002-extension-registry.md
- docs/blueprints/003-extension-registry.md
Implements: https://github.com/fuseml/fuseml/issues/74
> Feature: extension registry

- docs/blueprints/003-extension-registry.md
Update blueprint with implementation related changes:
* merged together the root element and instance sub-element of an extension record
* renamed `location` attribute to `zone`
* fixed endpoint types to `internal` and `external`
* renamed `service` field from service element to `resource` to avoid name clash
* added `category` field to service element
* updated extension reference examples to be more consistent with the examples
> feat: extension registry - update blueprint

- deployments/extensions.go
- Use Gateway namespace if provided
- During installation, if Step namespace is empty, use top level
namespace
> fixes for namespace handling

- deployments/extensions.go
The rules for finding the credentials are described in servicecredentials
section of the installation description file.
See https://github.com/fuseml/extensions/pull/21 for a description update
> feat: Fill in real credentials when registering an extension

- deployments/istio.go
Currently uninstalling FuseML leaves the cluster with Istio CRDs,
this change makes use of `kubectl` to delete every resource created
by istioctl, including the CRDs.
> fix: when uninstalling istio also remove its CRDs

- deployments/extensions.go
GET command for listing extensions now requires body (= query).
It has to be there even if it is empty
> fix: Correct the way list command is executed

- .github/workflows/ci.yml
- .github/workflows/lint_commit_messages.yml
- Makefile
- scripts/ci/mlflow-e2e.sh
* aligned scripts to the extension registry features
* enabled CI for release branches in github actions
* added a manual CI trigger in github actions
* updated mlflow-e2e CI scripts to make use of consistent
release branches across the board
> Update mlflow e2e CI

- .github/workflows/ci.yml
The base branch wasn't computed correctly.
> fix: e2e CI running on main branch

- deployments/extensions.go
> fix: Show URL for service installed as part of the extension

- deployments/extensions.go
- helpers/istio.go
See https://github.com/fuseml/extensions/pull/31 for example of new extension description, using these new features.
Related to https://github.com/fuseml/fuseml/issues/237
> Gateways for extensions

- scripts/ci/mlflow-e2e.sh
Requires https://github.com/fuseml/extensions/pull/42
> feat: Update CI to run seldon+tensorflow scenario

- deployments/extensions.go
- go.mod
- go.sum
- paas/install_client.go
- paas/ui/ui.go
This is a result of flaky internet connection in my home office...
> Added retries to HTTP calls

- deployments/tekton.go
The CI is sometimes failing when installing FuseML/tekton as when
it created the tekton config the webhook for validating the config
is not ready yet.
This change adds a retry in case of failure creating the tekton config.
It will retry 3 times with an interval that should be enough for the
webhook to be ready.
> fix: retry when applying the tekton config

- .github/workflows/ci.yml
- Makefile
- scripts/ci/mlflow-e2e.sh
keras codeset + mlflow-seldon-triton-e2e.yaml worklfow
Requires https://github.com/fuseml/examples/pull/29
> ci: Added a path to test Seldon-Core with Triton based workflow

- .github/workflows/ci.yml
- .github/workflows/get-fuseml-installer.yml
- .github/workflows/release.yml
- scripts/ci/mlflow-e2e.sh
Include test jobs, the same that are executed by the CI, as part of
the release workflow.
> ci: Run tests before release

- .github/workflows/ci.yml
- .github/workflows/get-fuseml-installer.yml
- .github/workflows/release.yml
- scripts/ci/mlflow-e2e.sh
Include test jobs, the same that are executed by the CI, as part of
the release workflow.
Backports #302
> [0.3] ci: Run tests before creating a release
