kubernetes/cluster.go
paas/install_client.go
scripts/knative-install.sh

Instead of checking for istio, check if Knative is installed to get the
system domain as knative is what provides the system domain when it is installed.

fix: Check for knative instead of istio for domain

---

paas/install_client.go
scripts/knative-install.sh

Also, instead of having a job configuring a domain for Knative when
it is installing, the domain configuration is set by FuseML during
its installation.

fix: When istio get domain IP from Istio gateway

---

.github/workflows/release.yml
Makefile

The pipeline builds the binaries, generates checksums and logs,
and attach them to a pre-release.
The pipeline is automatically triggered by creating a tag starting
with `v`.

ci: Adapt Carrier release pipeline for FuseML

---

CONTRIBUTING.md

Without this, people don't know how to get started with our
project.
We might want to expand this further by providing extra details
like communication channels, when they will be decided.
In the meantime, this is a good start for new contributors.
Closes: #23

docs: Add Contributing guide

---

CODE_OF_CONDUCT.md

This follows the contributor covenant guidelines [1].
Closes: #24
[1]: https://www.contributor-covenant.org/

docs: Add Code of Conduct

---

README.md

This is a minimal version of what needs to be done so the README does not contain nonsense.
Obviously changes should be much bigger for some production level of documentation....

fix: Update README to reflect current state of fuseml-installer

---

deployments/core.go
embedded-files/fuseml-core-deployment.yaml
paas/install_client.go

- Do not pass explicit namespace when creating deployment 
- Pass TEKTON_DASHBOARD_URL value to fuseml-core service

Fixes for core service deployment

---

embedded-files/fuseml-core-deployment.yaml

fuseml-core is updated automatically with 'dev' tag after every change,
see https://github.com/fuseml/fuseml-core/pull/57

fix: In development branch, fetch "dev" version of fuseml-core image

---

helpers/downloader.go
helpers/unzip.go
paas/install_cli.go

Unlike other systems, archive for windows is just zip.

fix: Download and unzip fuseml-core client for Windows

---

deployments/core.go
embedded-files/fuseml-core-deployment.yaml

This makes it clearer which user/password are the values about
It goes together with https://github.com/fuseml/fuseml-core/pull/61

fix: rename GITEA_USERNAME, GITEA_PASSWORD to GITEA_ADMIN_*

---

embedded-files/fuseml-core-deployment.yaml

This is fuseml-core can delete various resources forming FuseML
applications (secrets, serviceaccounts, inferenceservices etc.)
Closes #107
Do you think it is too powerful? I've made this after I saw the same is done for tekton: https://github.com/fuseml/fuseml/blob/main/embedded-files/tekton/install/admin-role.yaml#L87
According to this
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles
I think the admin privilegies are tied to the namespace (and not the whole cluster which would be rather scary) when defined this way (see  `kind: RoleBinding`)
_Allows super-user access to perform any action on any resource. When used in a ClusterRoleBinding, it gives full control over every resource in the cluster and in all namespaces. When used in a RoleBinding, it gives …

Give the admin rights to fuseml-core ServiceAccount

---

Makefile
cmd/internal/client/version.go
cmd/root.go
paas/client.go
paas/version/version.go

* version information is injected at build time
* add `fuseml-installer version` command to print information about
the installer version
```
> ./fuseml-installer version
Fuseml Installer
Version: v0.1
GitCommit: 8cd9dc17
Build Date: 2021-06-02T16:32:41Z
Go Version: go1.16
Compiler: gc
Platform: linux/amd64
```

Add version information to installer

---

embedded-files/fuseml-core-deployment.yaml
paas/install_cli.go

This applies for both
- fuseml-core docker image
- fuseml-core client

fix: Use stable fuseml-core-0.1 for fuseml-installer v0.1

---

Makefile
acceptance/acceptance_suite_test.go

It is supposed to be installed by fuseml-installer

fix: Do not run istio-install target by default

---

scripts/knative-install.sh

This allows KFServing and its prerequisites (Istio, KNative) to be
installed after FuseML and without impairing functionality.

fix: Set domain for KNative in installation script

---

README.md

The official docs have their own repo and website now, and a lot of
the information in README.md is duplicated there. To elliminate
duplication, the official docs are linked here instead.

fix: Reference official docs in README

---

.github/workflows/ci.yml
Makefile
scripts/ci/k3d-cluster.sh
scripts/ci/mlflow-e2e.sh
scripts/knative-install.sh

The mlflow-e2e job performs the following steps:
1. Build fuseml-installer
2. Create a k8s cluster (k3d)
3. Install KFServing
4. Install FuseML
5. Run the steps described on [1]
As this job also covers FuseML installation, replace it.
1. https://github.com/fuseml/fuseml-core#example

ci: Replace acceptance-tests with mlflow-e2e

---

cmd/internal/client/install.go
cmd/internal/client/upgrade.go
embedded-files/istio/istio-minimal-operator.yaml
paas/install_client.go
scripts/istio-minimal-install.sh
scripts/knative-install.sh

This PR includes the following changes with the intent to bring a more stable CI:
- When installing knative wait for all its deployments to be ready before proceeding.
- Lower memory/cpu footprint from Istio
- Switch default domain from "omg.howdoi.website" to "nip.io"

Fixes for CI instability

---

deployments/gitea.go
deployments/workloads.go

Also:
- Set APP_NAME to default value
- Remove NodePort services, instead use the default (ClusterIP)
Part of: https://github.com/fuseml/fuseml/issues/167

feat: Update gitea to version 1.14.3 and chart version to 4.0.1

---

deployments/extensions.go
docs/blueprints/001-installation-of-extensions.md
paas/install_client.go

Now if an extension has a defined requirement, all required
extensions should be automatically installed first.
When uninstalling, "top level" (those with dependencies) extensions
get uninstalled first.
Closes #188

feat: Add support for extension dependencies

---

cmd/internal/client/extensions.go
helpers/strings.go
paas/install_client.go

Until we have good knowledge if a dependent extension really is not
required by something else, simple solution is just uninstall what
was explicitly required by user (see #198)

fix:Different ways to handle uninstallation of dependencies

---

.github/workflows/ci.yml
.github/workflows/lint_commit_messages.yml
Makefile
scripts/ci/mlflow-e2e.sh

* aligned scripts to the extension registry features
* enabled CI for release branches in github actions
* added a manual CI trigger in github actions
* updated mlflow-e2e CI scripts to make use of consistent
release branches across the board
Backports: #212

ci: [2.0] Update mlflow e2e CI

---

embedded-files/fuseml-core-deployment.yaml
paas/config/config.go

* update the fuseml-core deployment to use the release fuseml-core
image tag instead of the `dev` tag
* update the default extension repository to point to the `release-*`
extension branch instead of `main`

feat: prepare for release v0.2

---

scripts/ci/k3d-cluster.sh

When characters other than [A-Za-z0-9-] are used for the branch name,
the CI fails because the generated k3d cluster name only allows those
characters.

ci: fix the k3d cluster name

---

scripts/ci/k3d-cluster.sh

When characters other than [A-Za-z0-9-] are used for the branch name,
the CI fails because the generated k3d cluster name only allows those
characters.
Backports: #215

ci: [0.2] fix the k3d cluster name

---

deployments/extensions.go

Print URL after creating a gateway and VirtualService. Closes #222
(cherry picked from commit 3521fb62890684f89eecd725c3922e136c11e864)

fix: Show URL for service installed as part of the extension

---

.github/workflows/ci.yml
.github/workflows/get-fuseml-installer.yml
install.sh

Add script for automatically downloading the correct `fuseml-installer`
binary according to the system it is being executed. By default the script
downloads the latest version and also upgrades the current binary if a new
version is available. If `TAG` is set it will download the binary from
the tag version.
This change also includes a CI job for testing the script/binary on
linux/macos/windows.
Fix: https://github.com/fuseml/fuseml/issues/207

feat: Add script for downloading fuseml-installer

---

deployments/extensions.go
helpers/exec.go

With verbosity>0, installer shows the kubectl command it is executing
when handling extensions. This way user has better idea what is going on,
especially when something goes wrong.

feat: Show which kubectl command is executed with verbose option

---

deployments/extensions.go
helpers/exec.go

With verbosity>0, installer shows the kubectl command it is executing
when handling extensions. This way user has better idea what is going on,
especially when something goes wrong.
(cherry picked from commit 111aee5dc32b700bcc5062647b0ca851b39f996a)
backport of https://github.com/fuseml/fuseml/pull/229

feat: [0.2] Show which kubectl command is executed with verbose option

---

embedded-files/fuseml-core-deployment.yaml

The persistent volume used to store badgerdb data can only be
mounted in max one pod at any given time. RollingUpdate upgrade
strategy doesn't work in these circumstances and needs to be
replaced with a Recreate strategy.
Closes https://github.com/fuseml/fuseml/issues/232

fix: use Recreate update strategy for fuseml-core

---

embedded-files/fuseml-core-deployment.yaml

The persistent volume used to store badgerdb data can only be
mounted in max one pod at any given time. RollingUpdate upgrade
strategy doesn't work in these circumstances and needs to be
replaced with a Recreate strategy.
Closes https://github.com/fuseml/fuseml/issues/232
Backports: #233

fix: [0.2] use Recreate update strategy for fuseml-core

---

embedded-files/fuseml-core-deployment.yaml

Update the fuseml-core deployment to use the v0.2.1 fuseml-core
image tag

feat: prepare for release v0.2.1

---

deployments/extensions.go
docs/blueprints/001-installation-of-extensions.md

Install step description can now contain Repo and Chart values,
identifying specific chart in a chart repository.
To use Repo+Chart combination, Location field must be empty.
Related to https://github.com/fuseml/fuseml/issues/237

feat: Allow installing helm charts from chart repositories

---

paas/install_client.go

Upgrade re-creates config map with some env variables,
and the system domain is needed for generating these.
Closes #242.

fix: Ensure there is a system domain for upgrade command

---

deployments/extensions.go
deployments/workloads.go

Enhance existing `fuseml-workloads` service account so it can read
information necessary for seldon-core based workflows.
Part of https://github.com/fuseml/fuseml/issues/238

fix: Update service account for running seldon-core workflows

---

cmd/internal/client/extensions.go
cmd/internal/client/install.go
cmd/internal/client/uninstall.go
deployments/extensions.go
paas/install_client.go

When installing/uninstalling extensions keep the same output format that
is used when installing FuseML.
Also, fixes references to `extension` where it should be `extensions`.

fix: extensions output formatting

---

deployments/extensions.go

For example for seldon-core, VirtualService is not created and it
does not make sense to show URL with wildcards.

fix: Print the service location only when VirtualService was created

---

deployments/workloads.go

Extend the set of permissions associated with the Tekton service
account to enable the OVMS predictor workflow step to create
necessary OVMS kubernetes resources.
Resolve: fuseml/fuseml#257

feat: add permissions to create OVMS related resources

---

paas/install_client.go

Upgrade re-creates config map with some env variables,
and the system domain is needed for generating these.
Closes #242.
(cherry picked from commit 589d64a3b1361b3291c442e280e11e950731ddfe)

[0.2] fix: Ensure there is a system domain for upgrade command

---

deployments/extensions.go
deployments/workloads.go
helpers/strings.go

TODO:
requires https://github.com/fuseml/extensions/pull/44

Make it possible to update the workflow role from extension

---

paas/install_client.go

For post-installation call of the installer, domain does not need
to be determined by checking the default provided by ingress but
rather by checking the VirtualService address of (already installed)
fuseml-core service.

feat: If a core service is already installed check it for domain

---

paas/install_client.go

Client is missing when calling `deployments.GetRegisteredExtensions` resulting
in failure when building.

fix: not enough arguments in call `deployments.GetRegisteredExtensions`

---

.github/workflows/ci.yml
Makefile
scripts/ci/mlflow-e2e.sh

keras codeset + mlflow-seldon-triton-e2e.yaml worklfow
(cherry picked from commit 5356c1cc72891c00fea7d7e47176718ee41ef9e1)
Backport of https://github.com/fuseml/fuseml/pull/293

[0.3] ci: Added a path to test Seldon-Core with Triton based workflow

---

.github/workflows/get-fuseml-installer.yml

The fuseml-installer test github action is currently triggered on
every possible push event on every branch: commits, but also tags. 
This has the effect that this test is triggered twice when a release
tag is published: once on the actual tag push event and a second time
as a dependency in the release action tree.
Specifying the list of branches in the action trigger excludes tags
from the list of events that trigger this workflow. It will only be
executed on PR push and when commits are merged.
Backports #304

[0.3] ci: don't test the installer twice on release
